/*
SQLyog - Free MySQL GUI v5.14
Host - 5.6.21 : Database - bhs_branches
*********************************************************************
Server version : 5.6.21
*/

SET NAMES utf8;

SET SQL_MODE='';
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO';

/*Table structure for table `tbl_branch_photo` */

DROP TABLE IF EXISTS `tbl_branch_photo`;

CREATE TABLE `tbl_branch_photo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `branch_id` int(11) DEFAULT NULL,
  `photo_file` varchar(255) DEFAULT NULL,
  `is_hidden` enum('Y','N') DEFAULT 'N',
  `date_created` datetime DEFAULT NULL,
  `date_modified` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `tbl_branch_photo` */

/*Table structure for table `tbl_branch_promo` */

DROP TABLE IF EXISTS `tbl_branch_promo`;

CREATE TABLE `tbl_branch_promo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `branch_id` int(11) DEFAULT NULL,
  `promo_title` varchar(255) DEFAULT NULL,
  `promo_content` text,
  `promo_photo_file` varchar(255) DEFAULT NULL,
  `promo_date_from` date DEFAULT NULL,
  `promo_date_to` date DEFAULT NULL,
  `is_hidden` enum('Y','N') DEFAULT 'N',
  `date_created` datetime DEFAULT NULL,
  `date_modified` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `tbl_branch_promo` */

/*Table structure for table `tbl_branches` */

DROP TABLE IF EXISTS `tbl_branches`;

CREATE TABLE `tbl_branches` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `province` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `branch_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `branch_code` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `address` tinytext CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `tel_no_1` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `tel_no_2` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `tel_no_3` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `mobile_no_1` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `mobile_no_2` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `mobile_no_3` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `email_add` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `website_url` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `fb_url` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `mgr_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `mgr_contact_no` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `mgr_email_add` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `operating_hrs` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `offpeak_hrs` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `peak_hrs` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `lat` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `long` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `date_created` datetime DEFAULT NULL,
  `date_modified` datetime DEFAULT NULL,
  `source_from` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `is_hidden` enum('Y','N') DEFAULT 'N',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=148 DEFAULT CHARSET=latin1;

/*Data for the table `tbl_branches` */

insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (1,'Laguna','BHS - GOLDEN CITY',NULL,'Golden City Subd., Sta. Rosa City, Laguna',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.288613','121.112580',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (2,'Laguna','BHS - NISSIN / BALIBAGO',NULL,'2nd Flr., UNit 2B Banawe de Sta. Rosa Bldg., Felix St., Balibago, Sta. Rosa City, Laguna (in front of Nissin-Monde Factory)','0939-908-4468',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.291183','121.099429',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (3,'Laguna','BHS - ROSARIO COMPLEX',NULL,'72-A Blk 13, Rosario Ave., Rosario Complex, San Pedro City, Laguna','0917-545-0832',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.364722','121.055556',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (4,'Laguna','BHS - SAN LORENZO',NULL,'2nd Floor Erika Bldg., Ph 1C San Lorenzo , Sta. Rosa, Laguna\r\n','0939-232-1414','0917-801-0301',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.284302','121.088893',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (5,'Laguna','BHS - SOUTH CITY',NULL,'Lot 18 Blk 53 San Pablo St., South City Homes Subd., Biñan City, Laguna','0920-962-2528','0928-713-2976',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.316027','121.079939',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (6,'Laguna','BHS - LM MARKET AREA',NULL,'LM Subd., Brgy., Market Area, Sta. Rosa City, Laguna','0917-500-3821',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.284302','121.088893',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (7,'Laguna','BHS - LOS BAÑOS',NULL,'Brgy. Batong Malake, Los Baños, Laguna\r\n(going to UPLB in front of BPI Family Bank after Robinson\'s Mall at Lopez Ave.)','0917-504-6577',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.151948','121.267836',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (8,'Laguna','BHS - PACITA COMPLEX',NULL,'Main Rd., Pacita Complex, San Pedro City, Laguna',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.364722','121.055556',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (9,'Laguna','BHS - PARIAN',NULL,'Parian Business Center, Parian, Calamba, Laguna','0905-300-7674',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.213078','121.149560',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (10,'Laguna','BHS - MAMATID',NULL,'Mabuhay Ph3, Mamatid, Cabuyao, Laguna','0905-300-7674',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.238430','121.152424',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (11,'Laguna','BHS - MAYAPA',NULL,'Mayapa, Calamba, Laguna','0905-300-7674',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.211445','121.123744',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (12,'Laguna','BHS - SAN PEDRO BAYAN',NULL,'2nd Floor ETG Business Center, Brgy. Poblacion, San Pedro City, Laguna','0933-525-5628',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.364722','121.055556',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (13,'Laguna','BHS - ELVINDA',NULL,'1st St., Sibulo, Brgy. Nueva, San Pedro City, Laguna',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.349995','121.062891',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (14,'Laguna','BHS - MAYAPA',NULL,'151 Don Bosco St., Mayapa, Calamba City, Laguna',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.210894','121.121982',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (15,'Laguna','BHS - OLIVARES',NULL,'Olivares, Biñan City, Laguna','0918-557-3349',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.333313','121.081835',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (16,'Laguna','BHS - SAN ANTONIO',NULL,'Brgy. San Antonio, Biñan City, Laguna',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.333282','121.093698',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (17,'Laguna','BHS - WALTERMART/CALAMBA',NULL,'National Highway Corner Real Street, Calamba City, Laguna','0915-253-0516',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.205902','121.155765',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (18,'Laguna','BHS - CHESTNUT',NULL,'L1 B1 Chestnut Subd., Tagaytay Rd., Brgy. Pulong Sta. Cruz, \r\nSta. Rosa City, Laguna','0917-887-6057','0932-869-4840',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.284302','121.088893',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (19,'Laguna','BHS - POOC',NULL,'114 Rizal Blvd. Brgy Pooc, Sta. Rosa City \r\n(2nd Floor of Julia\'s Laundry)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.284302','121.088893',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (20,'Laguna','BHS - STA. CRUZ',NULL,'Unit I & J 2nd Lvl Paradise Square Bldg., 1533 P. Guevarra St., Sta. Cruz, Laguna','0998-493-3714',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.287749','121.413697',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (21,'Laguna','BHS - BUCAL',NULL,'National Highway, Brgy. Bucal, Calamba City, Laguna','0917-547-3127',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.219571','121.139213',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (22,'Laguna','BHS - BRGY. IBABA',NULL,'Unit B Juni & Cristy Bldg., Gomez St., Brgy. Ibaba, Sta, Rosa, Laguna','0932-949-6124','0921-712-3440',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.284302','121.088893',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (23,'Laguna','BHS - San Pablo',NULL,'San Pablo, Laguna',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.064211','121.323337',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (24,'Cavite','BHS - TAGAYTAY / MENDEZ',NULL,'Unit 1 Aguinaldo Highway, Nasugbu Road Crossing, Tagaytay','0917-799-9364',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.115286','120.962116',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (25,'Cavite','BHS - TAGAYTAY ROTONDA',NULL,'Ridge Star Plaza, Crossing Silang East, Tagaytay','0919-510-8805',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.115286','120.962116',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (26,'Cavite','BHS - GEN. TRIAS BAYAN',NULL,'Gen. Trias, Cavite','0917-540-9637',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.383333','120.883333',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (27,'Cavite','BHS - GEN. TRIAS MANGGAHAN',NULL,'Manggahan, Gen. Trias, Cavite','0932-884-5622',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.291894','120.910956',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (28,'Cavite','BHS - FCIE DASMA',NULL,'In Front of FCIE, Dasmariñas, Cavite','0949-782-0920',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.299018','120.958970',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (29,'Cavite','BHS - PASEO DE CARMONA',NULL,'Unit II Great Luck Bldg., Paseo de Carmona, Carmona, Cavite','0932-612-8434',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.316667','121.050000',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (30,'Cavite','BHS - SOUTHVILLE',NULL,'Southville, Carmona, Cavite','0917-847-5287',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.316667','121.050000',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (31,'Cavite','BHS - DLSU DASMA',NULL,'DLSU Dasmariñas, Cavite','0927-795-5966',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.320550','120.961563',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (32,'Cavite','BHS - SALAWAG',NULL,'Salawag, Dasmariñas, Cavite','0921-519-2145',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.336515','120.981896',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (33,'Cavite','BHS - TANZA',NULL,'Tanza, Cavite','0915-880-1722',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.351967','120.838409',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (34,'Cavite','BHS - MALAGASANG',NULL,'Malagasang, Imus, Cavite','0921-406-7429',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.401681','120.926151',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (35,'Cavite','BHS - CAVITE CITY',NULL,'Cavite City, Cavite','0943-341-9979',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.479130','120.896963',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (36,'Cavite','BHS - ROSARIO',NULL,'Rosario, Cavite',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.416667','120.850000',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (37,'Cavite','BHS - NAIC',NULL,'2nd Floor Alea\'s Bldg, Cap Nazareno St., Naic, Cavite','0939-925-6096',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.315258','120.768413',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (38,'Cavite','BHS - KAWIT 1',NULL,'Centennial Road, Tabon I, Kawit, Cavite','0919-279-5026',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.426539','120.891986',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (39,'Cavite','BHS - PIEZA',NULL,'2nd Floor Fortuna Bldg., Pieza, Sampaloc 2, Dasmariñas, Cavite','0930-306-9992',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.282754','120.964643',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (40,'Cavite','BHS - CARMONA',NULL,'Carmona,Cavite','0922-865-5565','0906-908-6945',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.316667','121.050000',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (41,'Cavite','BHS - BAHAYANG PAGASA',NULL,'Bahayang Pagasa, Molino V, Bacoor, Cavite','0927-270-6282',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.398214','120.974143',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (42,'Cavite','BHS - BROOKSIDE',NULL,'Brookside Lane, Brgy. San Francisco, Gen. Trias, Cavite','0919-991-6224',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.281766','120.901550',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (43,'Cavite','BHS - AMAYA',NULL,'Amaya 1, Naic, Cavite','0929-645-7871',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.316667','120.766667',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (44,'Cavite','BHS - BANGKAL',NULL,'Bangkal, Carmona, Cavite',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.289167','121.011944',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (45,'Cavite','BHS - SILANG/TAGAYTAY',NULL,'Silang-Tagaytay Road, Silang, Cavite','0915-312-5634',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.106280','120.966680',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (46,'Cavite','BHS - TRECE MARTIREZ',NULL,'Trece Martirez, Cavite','0998-987-1399',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.283333','120.850000',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (47,'Cavite','BHS - SILANG-DASMA',NULL,'Silang-Dasmariñas Road, Silang, Cavite',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.223468','120.973631',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (48,'Cavite','BHS - PARADAHAN',NULL,'#381 Trece-Tanza Road, Brgy. Paradahan I, Tanza, Cavite','0905-328-1757',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.351967','120.838409',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (49,'Cavite','BHS - BUCANDALA',NULL,'Bucandala, Imus, Cavite','0919-417-0931',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.405374','120.924148',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (50,'Cavite','BHS - MENDEZ',NULL,'Mendez, Cavite','0917-809-2901',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.128611','120.905833',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (51,'Cavite','BHS - KAWIT 2',NULL,'Kawit, Cavite','0923-722-9886','0917-867-1475',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.433333','120.900000',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (52,'Cavite','BHS - LANCASTER',NULL,'Unit F & G MCC Bldg., Advincula Ave., Alapan II-A, Imus, Cavite','0999-880-3771',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.414392','120.900686',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (53,'Cavite','BHS - TRECE MARTIREZ',NULL,'Pampangueños Inn, Resort & Spa, Sitio Talisay, Brgy. Lapidario, Trece Martirez, Cavite','0917-809-0967','046-419-3216',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.479130','120.896963',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (54,'Cavite','BHS - DASMA AREA-C',NULL,'Area-C, Dasmariñas, Cavite','0935-303-2384','0917-392-4812',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.322130','120.969706',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (55,'Cavite','BHS - LALAAN 2',NULL,'#28 Pansol St., Malabag Toleda, Silang, Cavite','0922-835-8658',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.218309','120.972854',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (56,'Cavite','BHS - ZAPOTE',NULL,'#158 2nd Floor Burgos Bldg., Zapote 1, Bacoor, Cavite','0916-664-2316','046-683-4169',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.412993','120.973679',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (57,'Cavite','BHS - TANZA/TRECE',NULL,'Ricardo Lubigan Bldg., Brgy. de Ocampo, Tanza-Trece Road. Trece Martirez, Cavite','0915-723-1519',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.479130','120.896963',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (58,'Cavite','BHS - PANAPAAN',NULL,'Stall G Bianca arie Arcade, Km 17, Panapaan VI, Bacoor, Cavite','0927-270-6282',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.441965','120.953929',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (59,'Cavite','BHS - PUTING KAHOY SILANG',NULL,'Lot 1 Blk 2 Sta. Rosa Hills Subd., Puting Kahoy, Silang, Cavite','0916-286-5833',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.218309','120.972854',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (60,'Batangas','BHS - STO. TOMAS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (61,'Batangas','BHS - TANAUAN',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (62,'Batangas','BHS - TURBINA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (63,'Batangas','BHS - ALFONSO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (64,'Batangas','BHS - LIPA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (65,'Batangas','BHS - NASUGBU',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (66,'Batangas','BHS - TALISAY',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (67,'Metro Manila','BHS - CALOOCAN',NULL,'#510 MABINI ST., CALOOCAN CITY','09228395906',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.644488','120.974739',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (68,'Metro Manila','BHS - MAYPAJO',NULL,'1041 A. MABINI ST., MAYPAJO, CALOOCAN CITY','09996644000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.648047','120.973312',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (69,'Metro Manila','BHS - URCI',NULL,'URCI CMPD., CASIMIRO, LAS PINAS','09399192208',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.450257','120.991271',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (70,'Metro Manila','BHS - NAGA ROAD',NULL,'NAGA ROAD, LAS PINAS CITY','09399192208',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.463000','120.989306',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (71,'Metro Manila','BHS - MARCOS ALVAREZ',NULL,'MARCOS ALVAREZ, LAS PINAS CITY',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.428245','121.002621',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (72,'Metro Manila','BHS - SM SOUTHMALL',NULL,'IN FRONT OF SM SOUTHMALL, LAS PINAS CITY','09195246337',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.434763','121.011636',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (73,'Metro Manila','BHS - PHILAMLIFE',NULL,'2ND FLR RUBETAN BLDG., CV STAR AVE., PHILAMLIFE VILLAGE, LAS PINAS CITY','09399192208',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.449099','120.977945',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (74,'Metro Manila','BHS - PULANGLUPA UNO',NULL,'349 Real St. (Quirino Ave), Pulanglupa Uno, Las Pinas \r\nNear Shell Gas Station and on top of LBC Express','545-2215','0925-8716990','0915-9232215',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.464573','120.967189',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (75,'Metro Manila','BHS - PALANAN',NULL,'G1 DONA CARMEN BLDG, ARELLANO ST, PALANAN, MAKATI CITY','09259509958','025432620',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.576990','121.006725',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (76,'Metro Manila','BHS - BANGKAL	',NULL,'BANGKAL, MAKATI CITY',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.543800','121.011528',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (77,'Metro Manila','BHS - CHINO ROCES',NULL,'HEARTLAND BLDG., CHINO ROCES AVE., MAKATI CITY','09178001935',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.565280','121.011978',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (78,'Metro Manila','BHS - MANDALUYONG',NULL,'MANDALUYONG CITY',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.579444','121.035917',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (79,'Metro Manila','BHS - PANDACAN',NULL,'PANDACAN, MANILA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.589611','121.002998',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (80,'Metro Manila','BHS - TAYUMAN',NULL,'TAYUMAN, MANILA','09175363219',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.616657','120.982741',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (81,'Metro Manila','BHS - SAMPALOC - LOYOLA',NULL,'13841 SH LOYOLA COR JOCSON ST., SAMPALOC, MANILA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.610556','120.998333',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (82,'Metro Manila','BHS - TONDO',NULL,'PRITIL, TONDO, MANILA','09209204304',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.617773','120.969848',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (83,'Metro Manila','BHS - INTRAMUROS',NULL,'INTRAMUROS, MANILA','09177390518',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.589597','120.974726',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (84,'Metro Manila','BHS - PEDRO GIL',NULL,'2803-07 PEDRO GIL ST, STA ANA, MANILA','09175198869',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.581548','121.013675',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (85,'Metro Manila','BHS - FUGOSO',NULL,'1681 V. FUGOSO ST., STA. CRUZ, MANILA','09999920218','09176328366',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.607698','120.982860',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (86,'Metro Manila','BHS - STA. ANA',NULL,'STA. ANA, MANILA	',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.472234','121.027931',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (87,'Metro Manila','BHS - BINONDO',NULL,'464-B JABONEROS ST., BINONDO, MANILA','09176542426',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.598328','120.970512',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (88,'Metro Manila','BHS - MARIKINA',NULL,'MARIKINA CITY','09328672921',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.650730','121.102855',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (89,'Metro Manila','BHS - MARIKINA 2',NULL,'CONCEPCION UNO, MARIKINA CITY','09064194238','09291048881',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.646744','121.105159',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (90,'Metro Manila','BHS - SUSANA HEIGHTS',NULL,'SUSANA HEIGHTS, MUNTINLUPA CITY','09228404475',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.386750','121.045210',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (91,'Metro Manila','BHS - TUNASAN	',NULL,'TUNASAN, MUNTINLUPA CITY','09274993804',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.372545','121.036377',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (92,'Metro Manila','BHS - SOLDIERS HILLS',NULL,'SOLDIERS HILLS, MUNTINLUPA CITY','09179948080','(02) 938-6971',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.398330','121.045830',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (93,'Metro Manila','BHS - MADRIGAL ALABANG',NULL,'MADRIGAL, ALABANG, MUNTINLUPA CITY','09228851809',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.416689','121.024866',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (94,'Metro Manila','BHS - ALABANG',NULL,'ALABANG, MUNTINLUPA CITY',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.417034','121.047619',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (95,'Metro Manila','BHS - CITI ARCADE',NULL,'ITI ARCADE, ALABANG, MUNTINLUPA CITY','09082958010',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.417034','121.047619',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (96,'Metro Manila','BHS - WEST SERVICE ROAD',NULL,'UNIT 7 2ND FLR RB BLDG., DON JESUS BLVD/WEST SERVICE ROAD, CUPANG, MUNTINLUPA CITY','09082958010','09172554168',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.432446','121.045213',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (97,'Metro Manila','BHS - SM SUCAT',NULL,'UNIT E R&S BLDG., DR. A. SANTOS AVE., SAN DIONISIO, PARANAQUE CITY','09224270967',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.482094','120.996051',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (98,'Metro Manila','BHS - MERVILLE',NULL,'MERVILLE PARANAQUE CITY','09178825958',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.498213','121.024909',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (99,'Metro Manila','BHS - BETTERLIVING',NULL,'BETTERLIVING, PARANAQUE CITY',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.483738','121.033569',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (100,'Metro Manila','BHS - AGUIRRE AVE',NULL,'209 AGUIRRE AVE., BF HOMES, PARAÑAQUE CITY','09227697554',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.455598','121.011608',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (101,'Metro Manila','BHS - FRIENDSHIP ROAD',NULL,'FRIENDSHIP ROAD, PARANAQUE CITY','09189468652',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.440062','120.998203',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (102,'Metro Manila','BHS - MULTINATIONAL',NULL,'MULTINATIONAL VILLAGE, PARANAQUE CITY','09258083138',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.489044','121.001728',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (103,'Metro Manila','BHS - SUN VALLEY',NULL,'SUN VALLEY, SUCAT, PARANAQUE','09294562434',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.491371','121.037121',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (104,'Metro Manila','BHS - SUCAT',NULL,'SUCAT, PARANAQUE','09228604556',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.454611','121.049277',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (105,'Metro Manila','BHS - LA HUERTA',NULL,'LA HUERTA, PARANAQUE CITY',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.501183','120.991217',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (106,'Metro Manila','BHS - BACLARAN',NULL,'BACLARAN, PASAY CITY','09178011684',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.529416','120.997102',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (107,'Metro Manila','BHS - TAFT',NULL,'#2463-C TAFT AVE, PASAY CITY','09167402426',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.566179','120.993391',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (108,'Metro Manila','BHS - ORTIGAS EXT',NULL,'UNIT 5 2ND FLR JC BLDG., ORTIGAS EXT. PASIG CITY','09275638970','09099447342',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.588859','121.103994',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (109,'Metro Manila','BHS - KAPASIGAN',NULL,'#10 DR. SIXTO ANTONIO AVE., KAPASIGAN, PASIG CITY','09196927817',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.562119','121.076725',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (110,'Metro Manila','BHS - TANDANG SORA',NULL,'MINDANAO AVE COR TANDANG SORA, QUEZON CITY','(02)-453-2034','0916-707-0201',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.677033','121.031729',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (111,'Metro Manila','BHS - LIBIS',NULL,'UNIT 10 JW PLAZA 195 E. RODRIGUEZ JR. AVE., BAGUMBAYAN, LIBIS, QUEZON CITY','09196927817',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.616595','121.077221',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (112,'Metro Manila','BHS - FRISCO',NULL,'UNIT II A&B BLDG., FRISCO, SAN FRANCISCO DEL MONTE, QUEZON CITY','09253673812',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.640641','121.014874',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (113,'Metro Manila','BHS - EAST AVE',NULL,'#201 TEMPUS PLACE, MATALINO ST. COR. EAST AVE., QUEZON CITY	',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.642180','121.047080',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (114,'Metro Manila','BHS - FAIRVIEW',NULL,'FAIRVIEW, QUEZON CITY','09328670735',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.702179','121.068210',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (115,'Metro Manila','BHS - NOVALICHES',NULL,'NOVALICHES, QUEZON CITY','09328883602',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.721402','121.052141',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (116,'Metro Manila','BHS - VISAYAS AVE',NULL,'VISAYAS AVE, PASONG TAMO, QUEZON CITY','09204666493',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.665076','121.043566',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (117,'Metro Manila','BHS - LAGRO',NULL,'GRN FLR RM 013 FOUR M SQUARE BLDG., GREATER LAGRO, QUEZON CITY','09175557430','09475284662','09255525305',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.717418','121.055486',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (118,'Metro Manila','BHS - TAGUIG',NULL,'L42 B52 BRGY PINAGSAMA PH 2, TAGUIG','09291294432','09055008900',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.570983','121.022971',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (119,'Metro Manila','BHS - MALINTA',NULL,'#316 MCARTHUR HIGHWAY, MALINTA, VALENZUELA CITY','0947-366-0740',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.694823','120.964170',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (120,'Metro Manila','BHS - CUBAO',NULL,'2B ST. MARTIN BLDG., #17 WESTPOINT STREET,\r\nCUBAO, QUEZON CITY','(02) 510-0220','0905-485-9545',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.617290','121.059309',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (121,'Rizal','BHS - ANGONO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (122,'Rizal','BHS - ANTIPOLO 1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (123,'Rizal','BHS - ANTIPOLO 2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (124,'Rizal','BHS - CAINTA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (125,'North of Metro Manila','BHS - OLONGAPO',NULL,'2nd Flr., 510 Rizal Ave., East Tapinac, Olongapo City, Zambales','0917-401-2165',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.824786','120.293365',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (126,'North of Metro Manila','BHS - BALIUAG',NULL,'Baliuag, Bulacan',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.950000','120.883333',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (127,'North of Metro Manila','BHS - CALUMPIT',NULL,'Calumpit, Bulacan',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.916667','120.766667',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (128,'North of Metro Manila','BHS - TIKAY MALOLOS',NULL,'Malolos,Bulacan',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.852739','120.816038',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (129,'North of Metro Manila','BHS - BALANGA',NULL,'Balanga, Bataan',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.671013','120.497784',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (130,'North of Metro Manila','BHS - PLARIDEL',NULL,'Plaridel, Bulacan',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.883333','120.850000',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (131,'North of Metro Manila','BHS - SAN ILDEFONSO',NULL,'San Ildefonso, Bulacan',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'15.078889','120.941944',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (132,'North of Metro Manila','BHS - PLARIDEL',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (133,'North of Metro Manila','BHS - SAN LEONARDO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (134,'North of Metro Manila','BHS - SAN RAFAEL',NULL,'031A Pan-Phil Highway, Cruz na Daan, San Rafael, Bulacan',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'15.028516','120.934564',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (135,'North of Metro Manila','BHS - MEYCAUAYAN',NULL,'Sto. Niño, Meycauayan, Bulacan',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.764168','120.993054',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (136,'North of Metro Manila','BHS - SAN FERNANDO',NULL,'Poblacion, Gen. Hizon St., San Fernando, Pampanga',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'15.059394','120.656705',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (137,'North of Metro Manila','BHS - ANGELES',NULL,'Angeles City, Pampanga',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'15.144985','120.588703',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (138,'North of Metro Manila','BHS - TABANG',NULL,'Tabang, Guiguinto, Bulacan',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.833680','120.865685',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (139,'North of Metro Manila','BHS - BOCAUE',NULL,'Bocaue, Bulacan',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.805667','120.935788',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (140,'North of Metro Manila','BHS - STA MARIA',NULL,'Sta. Maria, Bulacan',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.816667','120.950000',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (141,'North of Metro Manila','BHS - MARILAO',NULL,'Marilao, Bulacan',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14.758056','120.948056',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (142,'North of Metro Manila','BHS - PULILAN',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (143,'North of Metro Manila','BHS - CABANATUAN',NULL,'Purok 2 Brgy. San Juan, ACCFA Dist. 2, Cabanatuan, Nueva Ecija',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'15.486505','120.973393',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (144,'North of Metro Manila','BHS - PAOMBONG',NULL,'019 (7 2FLR) Cristia Bayan St. Sitio Cristia Bayan, San Isidro 1, Paombong, Bulacan\r\nNEAR THE MARKET AND SAME BUILDING WITH VILLARICA PAWNSHOP',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'13.939357','121.613608',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (145,'North of Metro Manila','BHS - LUCENA 1',NULL,'2nd flr Delica Building Purok Happy Valley Maharlika Highway Red-V, Lucena City, Quezon Province',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'13.939357','121.613608',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (146,'North of Metro Manila','BHS - LUCENA 2',NULL,'Lucena City, Quezon Province',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'13.939357','121.613608',NULL,NULL,NULL,'N');
insert into `tbl_branches` (`id`,`province`,`branch_name`,`branch_code`,`address`,`tel_no_1`,`tel_no_2`,`tel_no_3`,`mobile_no_1`,`mobile_no_2`,`mobile_no_3`,`email_add`,`website_url`,`fb_url`,`mgr_name`,`mgr_contact_no`,`mgr_email_add`,`operating_hrs`,`offpeak_hrs`,`peak_hrs`,`lat`,`long`,`date_created`,`date_modified`,`source_from`,`is_hidden`) values (147,'North of Metro Manila','BHS - UNISAN',NULL,'PETRON KALILAYAN, BRGY ILAYA, KALILAYAN, UNISAN , QUEZON',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'13.833333','121.983333',NULL,NULL,NULL,'N');

/*Trigger structure for table `tbl_branches` */

DELIMITER $$;

DROP TRIGGER `insert`$$

CREATE TRIGGER `insert` AFTER INSERT ON `tbl_branches` FOR EACH ROW BEGIN
DECLARE datenow datetime;
SET @datenow = NOW();
UPDATE tbl_update SET date_modified = @datenow , hash_text = md5(@datenow) WHERE id = 1;
END$$


DROP TRIGGER `update`$$

CREATE TRIGGER `update` AFTER UPDATE ON `tbl_branches` FOR EACH ROW BEGIN
DECLARE datenow datetime;
SET @datenow = NOW();
UPDATE tbl_update SET date_modified = @datenow , hash_text = md5(@datenow) WHERE id = 1;
END$$


DROP TRIGGER `delete`$$

CREATE TRIGGER `delete` AFTER DELETE ON `tbl_branches` FOR EACH ROW BEGIN
DECLARE datenow datetime;
SET @datenow = NOW();
UPDATE tbl_update SET date_modified = @datenow , hash_text = md5(@datenow) WHERE id = 1;
END$$


DELIMITER ;$$

/*Table structure for table `tbl_update` */

DROP TABLE IF EXISTS `tbl_update`;

CREATE TABLE `tbl_update` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `param_name` varchar(255) DEFAULT NULL,
  `date_modified` datetime DEFAULT NULL,
  `hash_text` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Data for the table `tbl_update` */

insert into `tbl_update` (`id`,`param_name`,`date_modified`,`hash_text`) values (1,'branch','2015-10-26 16:40:46','518fd16ce1f5a79dc3f5d1c1b0787c9b');

SET SQL_MODE=@OLD_SQL_MODE;